# need for docker build
sudo: true

language: go
branches:
  only:
    - master

go: 1.10.x

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get -u golang.org/x/lint/golint #go get github.com/golang/lint/golint

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go vet -v $(go list ./... | grep -v /vendor/)
  - make container

deploy:
  - provider: script
    script:
      - ./deploy.sh
