apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  ports:
  - port: 8888
    name: proxy
  selector:
    app: gcsproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcsproxy
spec:
  selector:
    matchLabels:
      app: gcsproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: gcsproxy
    spec:
      containers:
      - name: gcsproxy
        image: quay.io/rootfs/gcsproxy:latest
        ports:
        - containerPort: 8888
          name: proxy
        volumeMounts:
        - name: json-key
          mountPath: /cfg
        command:
          - "/usr/bin/gcsproxy"
        args:
          - "-p"
          - ":8888"
          - "-c"
          - "/cfg/gcs.json" # must match configmap 
          - "-v"
      volumes:
        - name: json-key
          configMap:
            name: gcs-key
        
